### ISSUE TITLE
Insufficient label background

### ISSUE THREAD

**Issue by hazzas-99** [pierr3/vSMR#8]
I have noticed an issue with certain aircraft, where the second line has an insufficient background to be fully covered.
Examples:

![](http://harrysugden.net/screenshots/2015/04/2015-04-19_11-17-52.png)

![](http://harrysugden.net/screenshots/2015/04/2015-04-19_11-18-18.png)

**Comment by pierr3** [comment]
Somehow reassured that this doesn't only happens to me :p 
Will look into it.

**Comment by pierr3** [comment]
Should be fixed in 6dca57cd233af72cd1ff79d6520e622e31366621

**Comment by erikwachters** [comment]
I have still the same problem with the latest version (vSMR v1.1.0-rc2).

Erik

**Comment by TheoBearman** [comment]
1.1.0-rc2 did not have this fix included in it.

**Comment by pierr3** [comment]
I confirm, the fix will be included in the next release, probably on Friday.

**Comment by pierr3** [comment]
Not sure if my fix actually works, will keep this opened for testing.

**Comment by pierr3** [comment]
This will theoricaly be fixed with the new config based system.

**Comment by pierr3** [comment]
Issue has been found, and will be fixed in the next release, cf http://www.philosophicalgeek.com/2008/04/10/gettextextent-vs-drawtext-with-dt_calcrect/
